#!/usr/bin/env bash
# Bash script that loops from 1 to 10
bs=0
while [ $bs -le 9 ]
do
	bs=$((x + 1))
	if [ $bs == 4 ]
	then
		echo "bad luck"
	elif [ $bs == 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
