#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

bs=0
while [ $bs -le 19 ]
do
	bs=$((x + 1))
	echo $bs
	case $bs in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
done
