#!/usr/bin/env bash
# Check if running inside Docker container
# Modify the Docker container's hosts file
# Display an error message if not running inside Docker

if [ -f "/.dockerenv" ]; then
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
else
echo "This script is intended to be run inside a Docker container."
fi
